services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Set environment variables directly in the docker-compose file
    # environment:
    #   ENV_VARIABLE: ${ENV_VARIABLE}
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    # Set environment variables based on the .env file
    # env_file:
    #   - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 3030
      DATABASE_URL: postgres://postgres:password@postgres:5432/mydb
    ports:
      - 3030:3030
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    restart: unless-stopped
