export * from "./student-router.js";
export * from "./team-router.js";
export * from "./codes-router.js";
export * from "./coach-router.js";
export * from "./site-coordinator-router.js";
export * from "./admin-router.js";
export * from "./contest-registration-router.js";
export * from "./auth-router.js";
export * from "./email-router.js";
